language: c

before_install: 
 - sudo add-apt-repository ppa:mwild1/ppa -y
 - sudo apt-get update -y
 - sudo apt-get install luajit -y --force-yes
 - sudo apt-get install luarocks -y
 - sudo apt-get install strace -y
 - git submodule update --init --recursive

script:
 - make
 - make test

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@lists.sourceforge.net
    on_success: always
    on_failure: always
